name: marti_location_tracking
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #Navigation
  auto_route: ^9.2.2

  # Config
  equatable: ^2.0.7

  #Map
  location: ^7.0.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  flutter_polyline_points: ^2.1.0
  flutter_background_geolocation: ^4.16.6
  #Utility
  collection: ^1.18.0
  get_it: ^8.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1

  #State Management
  flutter_bloc: ^8.1.6

  #database
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #UI
  flutter_svg: ^2.0.16
  loader_overlay: ^5.0.0
  lottie: ^3.3.0
  google_fonts: ^6.2.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.2

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/image/
    - assets/svg/
    - assets/lottie/


  uses-material-design: true

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/image/marti_icon.png
  ios: true
  #min_sdk_android: 21 # android min sdk min:16, default 21
  # flutter_chat_ui: ^1.6.12
  remove_alpha_ios: true
